version: "3.8"
services:
  db:
    image: postgres:17
    container_name: easyattend_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: easyattend_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d easyattend_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data: